Pulling code from coreMLIR. Looks like I need to rebuild MLIR to get some libraries
LZJIT.cpp:(.text._ZN9LZJITPass14runOnOperationEv[_ZN9LZJITPass14runOnOperationEv]+0xdce): undefined reference to `mlir::translateModuleToLLVMIR(mlir::ModuleOp, llvm::LLVMContext&, llvm::StringRef)'
lib/LZJIT/libLZJIT.a(LZJIT.cpp.o): In function `LLVMInitializeNativeAsmParser()':
LZJIT.cpp:(.text._ZL29LLVMInitializeNativeAsmParserv+0xd): undefined reference to `LLVMInitializeX86AsmParser'
clang: error: linker command failed with exit code 1 (use -v to see invocation)