add fixups. We now emit _lean_main correctly. Now need to fix:
<stdin>:10:1: error: redefinition of symbol named 'l_IO_println___at_main___spec__1'
func @l_IO_println___at_main___spec__1(%x_1: f64, %x_2: !lz.value) -> !lz.value{
^
<stdin>:10:1: note: see current operation: "func"() ( {
^bb0(%arg0: f64, %arg1: !lz.value):  // no predecessors
  %0 = "std.call"(%arg0) {callee = @lean_float_to_string} : (f64) -> !lz.value
  %c10_i32 = "std.constant"() {value = 10 : i32} : () -> i32
  %1 = "std.call"(%0, %c10_i32) {callee = @lean_string_push} : (!lz.value, i32) -> !lz.value
  %2 = "std.call"(%1, %arg1) {callee = @l_IO_print___at_IO_println___spec__1} : (!lz.value, !lz.value) -> !lz.value
  "std.return"(%2) : (!lz.value) -> ()
}) {sym_name = "l_IO_println___at_main___spec__1", type = (f64, !lz.value) -> !lz.value} : () -> ()
<stdin>:2:1: note: see existing symbol definition here
func private @l_IO_println___at_main___spec__1(f64, !lz.value) -> !lz.value

LEAN's logic for tracking symbols seems different from mine, in ways I
don't understand.