WIP: get code to generate. Now running into linkage error
+ c++ -D LEAN_MULTI_THREAD -I/home/bollu/work/lean4/build/stage1/include exe.o /home/bollu/work/lz/lean-linking-incantations/lean-shell.o /home/bollu/work/lz/lean-linking-incantations/lib-includes/library.o -no-pie -Wl,--start-group -lleancpp -lInit -lStd -lLean -Wl,--end-group -L/home/bollu/work/lean4/build/stage1/lib/lean -lgmp -ldl -pthread -Wno-unused-command-line-argument -o exe.out
/usr/bin/ld: exe.o: in function `l_instInhabitedTree':
/home/bollu/work/lz/test/lambdapure/compile/<stdin>:23: undefined reference to `mkConstructor0'
/usr/bin/ld: exe.o: in function `l_treeToStr_match__1___rarg':
/home/bollu/work/lz/test/lambdapure/compile/<stdin>:35: undefined reference to `mkConstructor0'
/usr/bin/ld: exe.o: in function `l_main___closed__1':
/home/bollu/work/lz/test/lambdapure/compile/<stdin>:105: undefined reference to `mkConstructor0'